/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

/**
 *
 * @author tranvanloi
 */
public class JPanel_ThanhToanHoaDon extends javax.swing.JPanel {

    /**
     * Creates new form Jpanel_ThanhToanHoaDon
     */
    public JPanel_ThanhToanHoaDon() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        lblThongTinHoaDon = new javax.swing.JLabel();
        lblMaHoaDon = new javax.swing.JLabel();
        lblPhong = new javax.swing.JLabel();
        lblGioVao = new javax.swing.JLabel();
        lblGioRa = new javax.swing.JLabel();
        lblNgayTaoHoaDon = new javax.swing.JLabel();
<<<<<<< HEAD
        txtNgayTaoHoaDon = new javax.swing.JTextField();
        txtGiaRa = new javax.swing.JTextField();
        txtGioVao = new javax.swing.JTextField();
        txtPhong = new javax.swing.JTextField();
        txtMaHoaDon = new javax.swing.JTextField();
        lblTongTienThanhToan = new javax.swing.JLabel();
        lblTienPhong = new javax.swing.JLabel();
        txtTienPhong = new javax.swing.JTextField();
        txtTienDichVu = new javax.swing.JTextField();
        lblTienDichVu = new javax.swing.JLabel();
        lblTongTien = new javax.swing.JLabel();
        txtTongTien = new javax.swing.JTextField();
        txtTienNhan = new javax.swing.JTextField();
        lblTienNhan = new javax.swing.JLabel();
        lblTienThua = new javax.swing.JLabel();
        txtTienThua = new javax.swing.JTextField();
        btnThanhToan = new javax.swing.JButton();
        btnInHoaDon = new javax.swing.JButton();
=======
        lblTongTienThanhToan = new javax.swing.JLabel();
        lblTienPhong = new javax.swing.JLabel();
        lblTienDichVu = new javax.swing.JLabel();
        lblTongTien = new javax.swing.JLabel();
        lblTienNhan = new javax.swing.JLabel();
        lblTienThua = new javax.swing.JLabel();
        btnThanhToan = new javax.swing.JButton();
        btnInHoaDon = new javax.swing.JButton();
        lblMaHoaDon1 = new javax.swing.JLabel();
        lblPhong1 = new javax.swing.JLabel();
        lblGioVao1 = new javax.swing.JLabel();
        lblGioRa1 = new javax.swing.JLabel();
        lblTienDichVu1 = new javax.swing.JLabel();
        lblNgayTaoHoaDon1 = new javax.swing.JLabel();
        lblTongTien1 = new javax.swing.JLabel();
        lblTienPhong1 = new javax.swing.JLabel();
        lblTienNhan1 = new javax.swing.JLabel();
        lblTienThua1 = new javax.swing.JLabel();
>>>>>>> 45435bbf62c6ea729269c322a84918fbe28613d5
        jPanel1 = new javax.swing.JPanel();
        lblThongTinKhachHang = new javax.swing.JLabel();
        btnCapNhat = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        cmTenDichVu = new javax.swing.JComboBox<>();
        lblTenDichVu = new javax.swing.JLabel();
        lblSoLuong = new javax.swing.JLabel();
        cmbSoLuong = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_ChiTietDichVu = new javax.swing.JTable();
        lblChiTietDichVu = new javax.swing.JLabel();
        lblMaNhanVien = new javax.swing.JLabel();
<<<<<<< HEAD
        txtMaNhanVien = new javax.swing.JTextField();
        lblTenNhanVien = new javax.swing.JLabel();
        txtTenNhanVien = new javax.swing.JTextField();
        txtCCCD = new javax.swing.JTextField();
        lblCCCD = new javax.swing.JLabel();
        txtTenKhachHang = new javax.swing.JTextField();
        lblTenKhachHang = new javax.swing.JLabel();
        btnXoa = new javax.swing.JButton();
        lblThongTinNhanVien = new javax.swing.JLabel();
=======
        lblTenNhanVien = new javax.swing.JLabel();
        lblCCCD = new javax.swing.JLabel();
        lblTenKhachHang = new javax.swing.JLabel();
        btnXoa = new javax.swing.JButton();
        lblThongTinNhanVien = new javax.swing.JLabel();
        lblTenKhachHang1 = new javax.swing.JLabel();
        lblMaNhanVien1 = new javax.swing.JLabel();
        lblTenNhanVien1 = new javax.swing.JLabel();
        lblCCCD1 = new javax.swing.JLabel();
>>>>>>> 45435bbf62c6ea729269c322a84918fbe28613d5
        lblThanhToanHoaDon = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1250, 755));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        lblThongTinHoaDon.setFont(new java.awt.Font("ITF Devanagari", 1, 18)); // NOI18N
        lblThongTinHoaDon.setText("Thông tin hoá đơn");

        lblMaHoaDon.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        lblMaHoaDon.setText("Mã hoá đơn :");

        lblPhong.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        lblPhong.setText("Phòng :         ");

        lblGioVao.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        lblGioVao.setText("Giờ vào:");

        lblGioRa.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        lblGioRa.setText("Giờ ra:");

        lblNgayTaoHoaDon.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        lblNgayTaoHoaDon.setText("Ngày tạo hoá đơn :");

<<<<<<< HEAD
        txtNgayTaoHoaDon.setBackground(new java.awt.Color(204, 204, 204));
        txtNgayTaoHoaDon.setBorder(null);
        txtNgayTaoHoaDon.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtNgayTaoHoaDon.setEnabled(false);
        txtNgayTaoHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNgayTaoHoaDonActionPerformed(evt);
            }
        });

        txtGiaRa.setBackground(new java.awt.Color(204, 204, 204));
        txtGiaRa.setBorder(null);
        txtGiaRa.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtGiaRa.setEnabled(false);
        txtGiaRa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGiaRaActionPerformed(evt);
            }
        });

        txtGioVao.setBackground(new java.awt.Color(204, 204, 204));
        txtGioVao.setBorder(null);
        txtGioVao.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtGioVao.setEnabled(false);
        txtGioVao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGioVaoActionPerformed(evt);
            }
        });

        txtPhong.setBackground(new java.awt.Color(204, 204, 204));
        txtPhong.setBorder(null);
        txtPhong.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtPhong.setEnabled(false);
        txtPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhongActionPerformed(evt);
            }
        });

        txtMaHoaDon.setBackground(new java.awt.Color(204, 204, 204));
        txtMaHoaDon.setBorder(null);
        txtMaHoaDon.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtMaHoaDon.setEnabled(false);
        txtMaHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaHoaDonActionPerformed(evt);
            }
        });

=======
>>>>>>> 45435bbf62c6ea729269c322a84918fbe28613d5
        lblTongTienThanhToan.setFont(new java.awt.Font("ITF Devanagari", 1, 18)); // NOI18N
        lblTongTienThanhToan.setText("Tổng tiền thanh toán");

        lblTienPhong.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        lblTienPhong.setText("Tiền phòng :");

<<<<<<< HEAD
        txtTienPhong.setBackground(new java.awt.Color(204, 204, 204));
        txtTienPhong.setBorder(null);
        txtTienPhong.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtTienPhong.setEnabled(false);
        txtTienPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTienPhongActionPerformed(evt);
            }
        });

        txtTienDichVu.setBackground(new java.awt.Color(204, 204, 204));
        txtTienDichVu.setBorder(null);
        txtTienDichVu.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtTienDichVu.setEnabled(false);
        txtTienDichVu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTienDichVuActionPerformed(evt);
            }
        });

=======
>>>>>>> 45435bbf62c6ea729269c322a84918fbe28613d5
        lblTienDichVu.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        lblTienDichVu.setText("Tiền dịch vụ :");

        lblTongTien.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        lblTongTien.setText("Tổng tiền :");

<<<<<<< HEAD
        txtTongTien.setBackground(new java.awt.Color(204, 204, 204));
        txtTongTien.setBorder(null);
        txtTongTien.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtTongTien.setEnabled(false);
        txtTongTien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTongTienActionPerformed(evt);
            }
        });

        txtTienNhan.setBackground(new java.awt.Color(204, 204, 204));
        txtTienNhan.setBorder(null);
        txtTienNhan.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtTienNhan.setEnabled(false);
        txtTienNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTienNhanActionPerformed(evt);
            }
        });

=======
>>>>>>> 45435bbf62c6ea729269c322a84918fbe28613d5
        lblTienNhan.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        lblTienNhan.setText("Tiền nhận :");

        lblTienThua.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        lblTienThua.setText("Tiền thừa :");

<<<<<<< HEAD
        txtTienThua.setBackground(new java.awt.Color(204, 204, 204));
        txtTienThua.setBorder(null);
        txtTienThua.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtTienThua.setEnabled(false);
        txtTienThua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTienThuaActionPerformed(evt);
            }
        });

        btnThanhToan.setBackground(new java.awt.Color(162, 74, 74));
        btnThanhToan.setFont(new java.awt.Font("Helvetica Neue", 3, 13)); // NOI18N
        btnThanhToan.setForeground(new java.awt.Color(255, 255, 255));
        btnThanhToan.setIcon(new javax.swing.ImageIcon("/Users/tranvanloi/Desktop/1490863900_paypal.png")); // NOI18N
=======
        btnThanhToan.setBackground(new java.awt.Color(162, 74, 74));
        btnThanhToan.setFont(new java.awt.Font("Helvetica Neue", 3, 13)); // NOI18N
        btnThanhToan.setForeground(new java.awt.Color(255, 255, 255));
        btnThanhToan.setIcon(new javax.swing.ImageIcon("item/1490863900_paypal.png")); // NOI18N
>>>>>>> 45435bbf62c6ea729269c322a84918fbe28613d5
        btnThanhToan.setText("Thanh toán\n");
        btnThanhToan.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnThanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThanhToanActionPerformed(evt);
            }
        });

        btnInHoaDon.setBackground(new java.awt.Color(162, 74, 74));
        btnInHoaDon.setFont(new java.awt.Font("Helvetica Neue", 3, 13)); // NOI18N
        btnInHoaDon.setForeground(new java.awt.Color(255, 255, 255));
<<<<<<< HEAD
        btnInHoaDon.setIcon(new javax.swing.ImageIcon("/Users/tranvanloi/Desktop/print-24.png")); // NOI18N
        btnInHoaDon.setText("In hoá đơn\n");
        btnInHoaDon.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

=======
        btnInHoaDon.setIcon(new javax.swing.ImageIcon("item/print-24.png")); // NOI18N
        btnInHoaDon.setText("In hoá đơn\n");
        btnInHoaDon.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblMaHoaDon1.setFont(new java.awt.Font("ITF Devanagari", 1, 18)); // NOI18N
        lblMaHoaDon1.setPreferredSize(new java.awt.Dimension(42, 25));

        lblPhong1.setFont(new java.awt.Font("ITF Devanagari", 1, 18)); // NOI18N
        lblPhong1.setPreferredSize(new java.awt.Dimension(42, 25));

        lblGioVao1.setFont(new java.awt.Font("ITF Devanagari", 1, 18)); // NOI18N
        lblGioVao1.setPreferredSize(new java.awt.Dimension(42, 25));

        lblGioRa1.setFont(new java.awt.Font("ITF Devanagari", 1, 18)); // NOI18N
        lblGioRa1.setPreferredSize(new java.awt.Dimension(42, 25));

        lblTienDichVu1.setFont(new java.awt.Font("ITF Devanagari", 1, 18)); // NOI18N
        lblTienDichVu1.setPreferredSize(new java.awt.Dimension(42, 25));

        lblNgayTaoHoaDon1.setFont(new java.awt.Font("ITF Devanagari", 1, 18)); // NOI18N
        lblNgayTaoHoaDon1.setPreferredSize(new java.awt.Dimension(42, 25));

        lblTongTien1.setFont(new java.awt.Font("ITF Devanagari", 1, 18)); // NOI18N
        lblTongTien1.setPreferredSize(new java.awt.Dimension(42, 25));

        lblTienPhong1.setFont(new java.awt.Font("ITF Devanagari", 1, 18)); // NOI18N
        lblTienPhong1.setPreferredSize(new java.awt.Dimension(42, 25));

        lblTienNhan1.setFont(new java.awt.Font("ITF Devanagari", 1, 18)); // NOI18N
        lblTienNhan1.setPreferredSize(new java.awt.Dimension(42, 25));

        lblTienThua1.setFont(new java.awt.Font("ITF Devanagari", 1, 18)); // NOI18N
        lblTienThua1.setPreferredSize(new java.awt.Dimension(42, 25));

>>>>>>> 45435bbf62c6ea729269c322a84918fbe28613d5
        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
<<<<<<< HEAD
                .addGap(64, 64, 64)
                .addComponent(btnThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(btnInHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(79, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(26, 26, 26)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addGap(26, 26, 26)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblTongTien)
                                        .addComponent(lblTienThua)
                                        .addComponent(lblTienNhan))
                                    .addGap(22, 22, 22)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtTienNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(lblTienPhong)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtTienPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(lblTienDichVu)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtTienDichVu, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(92, 92, 92)
                                    .addComponent(txtTienThua, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(63, 63, 63))
                        .addGroup(jPanel2Layout.createSequentialGroup()
=======
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(btnThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblGioVao1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblPhong1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnInHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 26, Short.MAX_VALUE))
                            .addComponent(lblMaHoaDon1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTienThua1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTienNhan1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTienPhong1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTongTien1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTienDichVu1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(lblGioRa)
                        .addGap(91, 91, 91)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNgayTaoHoaDon1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblGioRa1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(26, 26, 26)
>>>>>>> 45435bbf62c6ea729269c322a84918fbe28613d5
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblThongTinHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblGioVao)
<<<<<<< HEAD
                                        .addComponent(lblGioRa)
                                        .addComponent(lblNgayTaoHoaDon)
                                        .addComponent(lblMaHoaDon)
                                        .addComponent(lblPhong)))
                                .addComponent(lblTongTienThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtMaHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtGioVao, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtGiaRa, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtNgayTaoHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addContainerGap(26, Short.MAX_VALUE)))
=======
                                        .addComponent(lblNgayTaoHoaDon)
                                        .addComponent(lblMaHoaDon)
                                        .addComponent(lblPhong)))
                                .addComponent(lblTongTienThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(52, 52, 52)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTongTien)
                                    .addComponent(lblTienThua)
                                    .addComponent(lblTienNhan))
                                .addComponent(lblTienPhong)
                                .addComponent(lblTienDichVu))))
                    .addContainerGap(136, Short.MAX_VALUE)))
>>>>>>> 45435bbf62c6ea729269c322a84918fbe28613d5
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
<<<<<<< HEAD
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50))
=======
                .addGap(79, 79, 79)
                .addComponent(lblMaHoaDon1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblPhong1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblGioVao1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGioRa)
                    .addComponent(lblGioRa1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblNgayTaoHoaDon1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTienPhong1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTienDichVu1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTongTien1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTienNhan1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTienThua1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
>>>>>>> 45435bbf62c6ea729269c322a84918fbe28613d5
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(41, 41, 41)
                    .addComponent(lblThongTinHoaDon)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
<<<<<<< HEAD
                            .addGap(48, 48, 48)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblPhong)
                                .addComponent(txtPhong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(17, 17, 17)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblGioVao)
                                .addComponent(txtGioVao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblGioRa)
                                .addComponent(txtGiaRa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblMaHoaDon)
                                .addComponent(txtMaHoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGap(17, 17, 17)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblNgayTaoHoaDon)
                        .addComponent(txtNgayTaoHoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(62, 62, 62)
                    .addComponent(lblTongTienThanhToan)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblTienPhong)
                        .addComponent(txtTienPhong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblTienDichVu)
                        .addComponent(txtTienDichVu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblTongTien)
                        .addComponent(txtTongTien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblTienNhan)
                        .addComponent(txtTienNhan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblTienThua)
                        .addComponent(txtTienThua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(159, Short.MAX_VALUE)))
=======
                            .addGap(50, 50, 50)
                            .addComponent(lblPhong)
                            .addGap(23, 23, 23)
                            .addComponent(lblGioVao))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(lblMaHoaDon)))
                    .addGap(54, 54, 54)
                    .addComponent(lblNgayTaoHoaDon)
                    .addGap(66, 66, 66)
                    .addComponent(lblTongTienThanhToan)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(lblTienPhong)
                    .addGap(18, 18, 18)
                    .addComponent(lblTienDichVu)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(lblTongTien)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(lblTienNhan)
                    .addGap(18, 18, 18)
                    .addComponent(lblTienThua)
                    .addContainerGap(98, Short.MAX_VALUE)))
>>>>>>> 45435bbf62c6ea729269c322a84918fbe28613d5
        );

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        lblThongTinKhachHang.setFont(new java.awt.Font("ITF Devanagari", 1, 18)); // NOI18N
        lblThongTinKhachHang.setText("Thông tin khách hàng");

        btnCapNhat.setBackground(new java.awt.Color(162, 74, 74));
        btnCapNhat.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        btnCapNhat.setForeground(new java.awt.Color(255, 255, 255));
<<<<<<< HEAD
        btnCapNhat.setIcon(new javax.swing.ImageIcon("/Users/tranvanloi/Desktop/update25.png")); // NOI18N
=======
        btnCapNhat.setIcon(new javax.swing.ImageIcon("item/update25.png")); // NOI18N
>>>>>>> 45435bbf62c6ea729269c322a84918fbe28613d5
        btnCapNhat.setText("Cập nhật\n");
        btnCapNhat.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnThem.setBackground(new java.awt.Color(162, 74, 74));
        btnThem.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        btnThem.setForeground(new java.awt.Color(255, 255, 255));
<<<<<<< HEAD
        btnThem.setIcon(new javax.swing.ImageIcon("/Users/tranvanloi/Desktop/add25.png")); // NOI18N
=======
        btnThem.setIcon(new javax.swing.ImageIcon("item/add25.png")); // NOI18N
>>>>>>> 45435bbf62c6ea729269c322a84918fbe28613d5
        btnThem.setText("Thêm\n");
        btnThem.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        cmTenDichVu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmTenDichVu.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cmTenDichVu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmTenDichVuActionPerformed(evt);
            }
        });

        lblTenDichVu.setFont(new java.awt.Font("ITF Devanagari", 1, 14)); // NOI18N
        lblTenDichVu.setText("Tên dịch vụ :");

        lblSoLuong.setFont(new java.awt.Font("ITF Devanagari", 1, 14)); // NOI18N
        lblSoLuong.setText("Số lượng:");

        cmbSoLuong.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbSoLuong.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cmbSoLuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSoLuongActionPerformed(evt);
            }
        });

        tbl_ChiTietDichVu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Tên dịch vụ", "Số lượng", "Giá", "Thành tiền"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Long.class, java.lang.Float.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_ChiTietDichVu.setGridColor(new java.awt.Color(220, 155, 155));
        jScrollPane1.setViewportView(tbl_ChiTietDichVu);

        lblChiTietDichVu.setFont(new java.awt.Font("ITF Devanagari", 1, 18)); // NOI18N
        lblChiTietDichVu.setText("Chi tiết dịch vụ");

        lblMaNhanVien.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        lblMaNhanVien.setText("Mã nhân viên :");

<<<<<<< HEAD
        txtMaNhanVien.setBackground(new java.awt.Color(204, 204, 204));
        txtMaNhanVien.setBorder(null);
        txtMaNhanVien.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtMaNhanVien.setEnabled(false);
        txtMaNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaNhanVienActionPerformed(evt);
            }
        });

        lblTenNhanVien.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        lblTenNhanVien.setText("Tên nhân viên :");

        txtTenNhanVien.setBackground(new java.awt.Color(204, 204, 204));
        txtTenNhanVien.setBorder(null);
        txtTenNhanVien.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtTenNhanVien.setEnabled(false);
        txtTenNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenNhanVienActionPerformed(evt);
            }
        });

        txtCCCD.setBackground(new java.awt.Color(204, 204, 204));
        txtCCCD.setBorder(null);
        txtCCCD.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtCCCD.setEnabled(false);
        txtCCCD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCCCDActionPerformed(evt);
            }
        });

        lblCCCD.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        lblCCCD.setText("CCCD :");

        txtTenKhachHang.setBackground(new java.awt.Color(204, 204, 204));
        txtTenKhachHang.setBorder(null);
        txtTenKhachHang.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtTenKhachHang.setEnabled(false);
        txtTenKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenKhachHangActionPerformed(evt);
            }
        });

=======
        lblTenNhanVien.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        lblTenNhanVien.setText("Tên nhân viên :");

        lblCCCD.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        lblCCCD.setText("CCCD :");

>>>>>>> 45435bbf62c6ea729269c322a84918fbe28613d5
        lblTenKhachHang.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        lblTenKhachHang.setText("Tên khách hàng :");

        btnXoa.setBackground(new java.awt.Color(162, 74, 74));
        btnXoa.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        btnXoa.setForeground(new java.awt.Color(255, 255, 255));
<<<<<<< HEAD
        btnXoa.setIcon(new javax.swing.ImageIcon("/Users/tranvanloi/Desktop/delete25.png")); // NOI18N
=======
        btnXoa.setIcon(new javax.swing.ImageIcon("item/delete25.png")); // NOI18N
>>>>>>> 45435bbf62c6ea729269c322a84918fbe28613d5
        btnXoa.setText("Xoá\n");
        btnXoa.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblThongTinNhanVien.setFont(new java.awt.Font("ITF Devanagari", 1, 18)); // NOI18N
        lblThongTinNhanVien.setText("Thông tin nhân viên");

<<<<<<< HEAD
=======
        lblTenKhachHang1.setFont(new java.awt.Font("ITF Devanagari", 1, 18)); // NOI18N
        lblTenKhachHang1.setPreferredSize(new java.awt.Dimension(42, 30));
        lblTenKhachHang1.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        lblMaNhanVien1.setFont(new java.awt.Font("ITF Devanagari", 1, 18)); // NOI18N
        lblMaNhanVien1.setPreferredSize(new java.awt.Dimension(42, 30));
        lblMaNhanVien1.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        lblTenNhanVien1.setFont(new java.awt.Font("ITF Devanagari", 1, 18)); // NOI18N
        lblTenNhanVien1.setPreferredSize(new java.awt.Dimension(42, 30));
        lblTenNhanVien1.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        lblCCCD1.setFont(new java.awt.Font("ITF Devanagari", 1, 18)); // NOI18N
        lblCCCD1.setPreferredSize(new java.awt.Dimension(42, 30));
        lblCCCD1.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

>>>>>>> 45435bbf62c6ea729269c322a84918fbe28613d5
        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
<<<<<<< HEAD
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 683, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblMaNhanVien)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtMaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(lblTenNhanVien)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTenNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblTenKhachHang)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtTenKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCCCD)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(106, 106, 106)
                                        .addComponent(txtCCCD, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblThongTinKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblThongTinNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblChiTietDichVu, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(28, 28, 28))
=======
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblMaNhanVien)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblMaNhanVien1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblTenKhachHang)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblTenKhachHang1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblTenNhanVien)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblTenNhanVien1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblCCCD)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblCCCD1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblThongTinKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblThongTinNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblChiTietDichVu, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 695, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 17, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82)
                .addComponent(btnCapNhat, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
>>>>>>> 45435bbf62c6ea729269c322a84918fbe28613d5
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(68, 68, 68)
                    .addComponent(lblTenDichVu, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(cmTenDichVu, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(33, 33, 33)
                    .addComponent(lblSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(cmbSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
<<<<<<< HEAD
                    .addContainerGap(148, Short.MAX_VALUE))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(82, 82, 82)
                    .addComponent(btnCapNhat, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(64, 64, 64)
                    .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(115, 115, 115)))
=======
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
>>>>>>> 45435bbf62c6ea729269c322a84918fbe28613d5
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblThongTinKhachHang)
<<<<<<< HEAD
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTenKhachHang)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtTenKhachHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblCCCD)
                        .addComponent(txtCCCD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23)
                .addComponent(lblThongTinNhanVien)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMaNhanVien)
                    .addComponent(txtMaNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTenNhanVien)
                    .addComponent(txtTenNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addComponent(lblChiTietDichVu, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(166, Short.MAX_VALUE))
=======
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTenKhachHang)
                            .addComponent(lblCCCD)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(lblTenKhachHang1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(lblCCCD1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21)
                .addComponent(lblThongTinNhanVien)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMaNhanVien)
                            .addComponent(lblTenNhanVien)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblMaNhanVien1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblTenNhanVien1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(lblChiTietDichVu, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnCapNhat)
                    .addComponent(btnXoa))
                .addGap(31, 31, 31))
>>>>>>> 45435bbf62c6ea729269c322a84918fbe28613d5
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(527, 527, 527)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblTenDichVu)
                        .addComponent(cmTenDichVu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblSoLuong)
                        .addComponent(cmbSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
<<<<<<< HEAD
                    .addGap(26, 26, 26)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnThem)
                        .addComponent(btnCapNhat)
                        .addComponent(btnXoa))
                    .addContainerGap(44, Short.MAX_VALUE)))
=======
                    .addContainerGap(94, Short.MAX_VALUE)))
>>>>>>> 45435bbf62c6ea729269c322a84918fbe28613d5
        );

        lblThanhToanHoaDon.setFont(new java.awt.Font("Helvetica", 1, 30)); // NOI18N
        lblThanhToanHoaDon.setText("Thanh Toán Hoá Đơn");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
<<<<<<< HEAD
                .addGap(14, 14, 14)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblThanhToanHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(427, 427, 427))
=======
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(351, 351, 351)
                        .addComponent(lblThanhToanHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(158, Short.MAX_VALUE))
>>>>>>> 45435bbf62c6ea729269c322a84918fbe28613d5
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
<<<<<<< HEAD
                .addGap(13, 13, 13)
                .addComponent(lblThanhToanHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(13, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtNgayTaoHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNgayTaoHoaDonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNgayTaoHoaDonActionPerformed

    private void txtGiaRaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGiaRaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGiaRaActionPerformed

    private void txtGioVaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGioVaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGioVaoActionPerformed

    private void txtPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhongActionPerformed

    private void txtMaHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaHoaDonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaHoaDonActionPerformed

    private void txtTienPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTienPhongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTienPhongActionPerformed

    private void txtTienDichVuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTienDichVuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTienDichVuActionPerformed

    private void txtTongTienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTongTienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTongTienActionPerformed

    private void txtTienNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTienNhanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTienNhanActionPerformed

    private void txtTienThuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTienThuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTienThuaActionPerformed

=======
                .addGap(25, 25, 25)
                .addComponent(lblThanhToanHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(85, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

>>>>>>> 45435bbf62c6ea729269c322a84918fbe28613d5
    private void btnThanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThanhToanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnThanhToanActionPerformed

    private void cmTenDichVuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmTenDichVuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmTenDichVuActionPerformed

    private void cmbSoLuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSoLuongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbSoLuongActionPerformed

<<<<<<< HEAD
    private void txtMaNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaNhanVienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaNhanVienActionPerformed

    private void txtTenNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenNhanVienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenNhanVienActionPerformed

    private void txtCCCDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCCCDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCCCDActionPerformed

    private void txtTenKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenKhachHangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenKhachHangActionPerformed

=======
>>>>>>> 45435bbf62c6ea729269c322a84918fbe28613d5

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnInHoaDon;
    private javax.swing.JButton btnThanhToan;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cmTenDichVu;
    private javax.swing.JComboBox<String> cmbSoLuong;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCCCD;
<<<<<<< HEAD
    private javax.swing.JLabel lblChiTietDichVu;
    private javax.swing.JLabel lblGioRa;
    private javax.swing.JLabel lblGioVao;
    private javax.swing.JLabel lblMaHoaDon;
    private javax.swing.JLabel lblMaNhanVien;
    private javax.swing.JLabel lblNgayTaoHoaDon;
    private javax.swing.JLabel lblPhong;
    private javax.swing.JLabel lblSoLuong;
    private javax.swing.JLabel lblTenDichVu;
    private javax.swing.JLabel lblTenKhachHang;
    private javax.swing.JLabel lblTenNhanVien;
=======
    private javax.swing.JLabel lblCCCD1;
    private javax.swing.JLabel lblChiTietDichVu;
    private javax.swing.JLabel lblGioRa;
    private javax.swing.JLabel lblGioRa1;
    private javax.swing.JLabel lblGioVao;
    private javax.swing.JLabel lblGioVao1;
    private javax.swing.JLabel lblMaHoaDon;
    private javax.swing.JLabel lblMaHoaDon1;
    private javax.swing.JLabel lblMaNhanVien;
    private javax.swing.JLabel lblMaNhanVien1;
    private javax.swing.JLabel lblNgayTaoHoaDon;
    private javax.swing.JLabel lblNgayTaoHoaDon1;
    private javax.swing.JLabel lblPhong;
    private javax.swing.JLabel lblPhong1;
    private javax.swing.JLabel lblSoLuong;
    private javax.swing.JLabel lblTenDichVu;
    private javax.swing.JLabel lblTenKhachHang;
    private javax.swing.JLabel lblTenKhachHang1;
    private javax.swing.JLabel lblTenNhanVien;
    private javax.swing.JLabel lblTenNhanVien1;
>>>>>>> 45435bbf62c6ea729269c322a84918fbe28613d5
    private javax.swing.JLabel lblThanhToanHoaDon;
    private javax.swing.JLabel lblThongTinHoaDon;
    private javax.swing.JLabel lblThongTinKhachHang;
    private javax.swing.JLabel lblThongTinNhanVien;
    private javax.swing.JLabel lblTienDichVu;
<<<<<<< HEAD
    private javax.swing.JLabel lblTienNhan;
    private javax.swing.JLabel lblTienPhong;
    private javax.swing.JLabel lblTienThua;
    private javax.swing.JLabel lblTongTien;
    private javax.swing.JLabel lblTongTienThanhToan;
    private javax.swing.JTable tbl_ChiTietDichVu;
    private javax.swing.JTextField txtCCCD;
    private javax.swing.JTextField txtGiaRa;
    private javax.swing.JTextField txtGioVao;
    private javax.swing.JTextField txtMaHoaDon;
    private javax.swing.JTextField txtMaNhanVien;
    private javax.swing.JTextField txtNgayTaoHoaDon;
    private javax.swing.JTextField txtPhong;
    private javax.swing.JTextField txtTenKhachHang;
    private javax.swing.JTextField txtTenNhanVien;
    private javax.swing.JTextField txtTienDichVu;
    private javax.swing.JTextField txtTienNhan;
    private javax.swing.JTextField txtTienPhong;
    private javax.swing.JTextField txtTienThua;
    private javax.swing.JTextField txtTongTien;
=======
    private javax.swing.JLabel lblTienDichVu1;
    private javax.swing.JLabel lblTienNhan;
    private javax.swing.JLabel lblTienNhan1;
    private javax.swing.JLabel lblTienPhong;
    private javax.swing.JLabel lblTienPhong1;
    private javax.swing.JLabel lblTienThua;
    private javax.swing.JLabel lblTienThua1;
    private javax.swing.JLabel lblTongTien;
    private javax.swing.JLabel lblTongTien1;
    private javax.swing.JLabel lblTongTienThanhToan;
    private javax.swing.JTable tbl_ChiTietDichVu;
>>>>>>> 45435bbf62c6ea729269c322a84918fbe28613d5
    // End of variables declaration//GEN-END:variables
}
